/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Lightweight public health check.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return scoring weights and app configuration.
         *
         *     Allows the frontend to stay in sync with backend weight configuration
         *     instead of hardcoding weight percentages.
         */
        get: operations["get_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Health
         * @description Detailed health check including circuit breakers and cache stats.
         */
        get: operations["admin_health_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lineage
         * @description Return full lineage information for the given token mint.
         */
        get: operations["get_lineage_lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Lineage
         * @description Analyse multiple mints concurrently (max 10, 3 at a time).
         */
        post: operations["batch_lineage_lineage_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search Solana tokens by name or symbol via DexScreener.
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployer/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical behaviour profile for a deployer wallet
         * @description Return historical behaviour statistics for a Solana deployer wallet.
         */
        get: operations["get_deployer_profile_deployer__address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator/{fingerprint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cross-wallet operator damage ledger
         * @description Return the aggregated damage ledger for an operator DNA fingerprint.
         */
        get: operations["get_operator_impact_operator__fingerprint__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/{mint}/sol-trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Post-rug SOL capital flow trace
         * @description Return (or trigger) the SOL flow trace for a rugged token.
         */
        get: operations["get_sol_trace_lineage__mint__sol_trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/{mint}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll cached bundle extraction report for a token
         * @description Return the cached bundle extraction report without triggering new RPC calls.
         *
         *     The bundle report is computed during the main ``/lineage`` scan and
         *     persisted to the DB.  If the inline 30-second cap was hit, the full
         *     analysis completes in the background and this endpoint exposes the
         *     result once available.  Returns 404 if analysis has not yet run.
         */
        get: operations["get_lineage_bundle_lineage__mint__bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartel/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find cartel community for a deployer wallet
         * @description Find the cartel community containing a deployer wallet.
         */
        get: operations["cartel_search_cartel_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartel/{community_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cartel community by ID
         * @description Return a cartel community by its stable community_id.
         */
        get: operations["get_cartel_community_cartel__community_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartel/{deployer}/financial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Financial coordination graph for a deployer
         * @description Build and return the financial coordination graph for a deployer.
         *
         *     Runs the 3 financial signals (funding_link, shared_lp, sniper_ring)
         *     on-demand and returns a summary with scoring and edge details.
         */
        get: operations["cartel_financial_graph_cartel__deployer__financial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundle/{mint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forensic bundle wallet analysis for a token launch
         * @description Detect Jito bundle wallets at token launch and trace their SOL flows.
         *
         *     Returns the list of early coordinated buyers, which ones were funded by
         *     the deployer, how much SOL flowed back, and an extraction verdict.
         */
        get: operations["get_bundle_report_bundle__mint__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/{mint}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multi-generation graph data for a token family
         * @description Return edge/node lists suitable for graph rendering.
         *
         *     Uses the cached lineage result (or triggers a fresh analysis) and
         *     exposes ``parent_mint`` + ``generation`` on each node.
         */
        get: operations["get_lineage_graph_lineage__mint__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/{mint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI forensic analysis — risk score, narrative, wallet classifications
         * @description Generate an AI-powered forensic narrative from bundle + SOL flow + lineage data.
         *
         *     Calls Anthropic Claude with all available on-chain evidence and returns:
         *     - risk_score (0-100)
         *     - confidence (low / medium / high)
         *     - rug_pattern classification
         *     - narrative (2-4 sentence explanation)
         *     - key_findings (3-6 bullet points)
         *     - wallet_classifications
         *     - operator_hypothesis
         */
        get: operations["get_ai_analysis_analyze__mint__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/{mint}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI forensic analysis with SSE progress events
         * @description Same as /analyze/{mint} but streams progress via Server-Sent Events.
         *
         *     Events:
         *       step  {"step":"lineage"|"bundle"|"sol_flow"|"ai", "status":"running"|"done", "ms":<int>}
         *       complete  <full AnalyzeResponse JSON>
         *       error  {"detail":"..."}
         */
        get: operations["stream_ai_analysis_analyze__mint__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{mint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conversational forensic chat for a specific token (SSE streaming)
         * @description Stream a Claude reply about a specific token's forensic analysis.
         *
         *     Events:
         *       token  {"text": "<chunk>"}
         *       done   {}
         *       error  {"detail": "..."}
         */
        post: operations["forensic_chat_chat__mint__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth Login
         * @description Upsert a user identified by their Privy ID.
         *     Returns the user record including the API key.
         *     Call this from the frontend after Privy.authenticate().
         */
        post: operations["auth_login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Me
         * @description Return current user info. Requires X-API-Key header.
         */
        get: operations["auth_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Watches
         * @description Return user's watches. Requires X-API-Key header.
         */
        get: operations["auth_watches_auth_watches_get"];
        put?: never;
        /**
         * Auth Add Watch
         * @description Add a watch for the current user. Requires X-API-Key header.
         */
        post: operations["auth_add_watch_auth_watches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/watches/{watch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Auth Remove Watch
         * @description Delete a watch by id. Requires X-API-Key header.
         */
        delete: operations["auth_remove_watch_auth_watches__watch_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Side-by-side similarity analysis between two tokens
         * @description Compare two tokens across name, symbol, image, deployer, temporal and lineage dimensions.
         */
        get: operations["compare_tokens_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate activity statistics for the last 24 hours
         * @description Return aggregate intelligence stats: rug count, active deployers, top narratives, etc.
         *
         *     Results are cached in-process for 60 seconds to keep DB load minimal.
         */
        get: operations["get_global_stats_stats_global_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Human-readable 2-sentence intelligence brief from the last 24 h stats
         * @description Compose a short English summary from GlobalStats for display in the mobile AI Brief card.
         */
        get: operations["get_stats_brief_stats_brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BatchLineageRequest
         * @description Request body for the batch lineage endpoint.
         */
        BatchLineageRequest: {
            /**
             * Mints
             * @description 1-10 Solana mint addresses
             */
            mints: string[];
        };
        /**
         * BatchLineageResponse
         * @description Response for a batch lineage request.
         */
        BatchLineageResponse: {
            /**
             * Results
             * @description Mapping mint → LineageResult on success or error string on failure
             */
            results: {
                [key: string]: components["schemas"]["LineageResult"] | string;
            };
        };
        /**
         * BundleExtractionReport
         * @description Forensic bundle extraction report — on-chain proof required before team attribution.
         */
        BundleExtractionReport: {
            /** Mint */
            mint: string;
            /** Deployer */
            deployer: string;
            /** Launch Slot */
            launch_slot?: number | null;
            /**
             * Bundle Wallets
             * @description Per-wallet forensic breakdown
             */
            bundle_wallets?: components["schemas"]["BundleWalletAnalysis"][];
            /**
             * Confirmed Team Wallets
             * @description Wallets with direct on-chain deployer link
             */
            confirmed_team_wallets?: string[];
            /**
             * Suspected Team Wallets
             * @description Wallets with indirect / circumstantial deployer link
             */
            suspected_team_wallets?: string[];
            /**
             * Coordinated Dump Wallets
             * @description Coordinated wallets without proved deployer link
             */
            coordinated_dump_wallets?: string[];
            /**
             * Early Buyer Wallets
             * @description Wallets with no adverse signals
             */
            early_buyer_wallets?: string[];
            /**
             * Total Sol Spent By Bundle
             * @default 0
             */
            total_sol_spent_by_bundle: number;
            /**
             * Total Sol Extracted Confirmed
             * @description SOL confirmed returning to deployer-linked addresses
             * @default 0
             */
            total_sol_extracted_confirmed: number;
            /**
             * Total Usd Extracted
             * @description USD at time of analysis
             */
            total_usd_extracted?: number | null;
            /**
             * Common Prefund Source
             * @description Address that funded multiple bundle wallets before launch
             */
            common_prefund_source?: string | null;
            /**
             * Factory Address
             * @description Wallet that funded ≥2 bundle wallets and/or the deployer — the orchestrating entity behind the launch
             */
            factory_address?: string | null;
            /**
             * Factory Funded Deployer
             * @description factory_address also sent SOL to the deployer wallet before launch
             * @default false
             */
            factory_funded_deployer: boolean;
            /**
             * Factory Sniper Wallets
             * @description Bundle wallets confirmed funded by factory_address
             */
            factory_sniper_wallets?: string[];
            /**
             * Common Sink Wallets
             * @description Destination wallets that received funds from ≥2 bundle wallets
             */
            common_sink_wallets?: string[];
            /**
             * Coordinated Sell Detected
             * @description ≥3 bundle wallets sold within 5 slots of each other
             * @default false
             */
            coordinated_sell_detected: boolean;
            /**
             * Overall Verdict
             * @description Global extraction verdict — requires concrete proof for higher severity
             * @default early_buyers_no_link_proven
             * @enum {string}
             */
            overall_verdict: "confirmed_team_extraction" | "suspected_team_extraction" | "coordinated_dump_unknown_team" | "early_buyers_no_link_proven";
            /**
             * Evidence Chain
             * @description Ordered list of on-chain evidence items supporting the verdict
             */
            evidence_chain?: string[];
            /**
             * Analysis Timestamp
             * Format: date-time
             */
            analysis_timestamp?: string;
        };
        /**
         * BundleWalletAnalysis
         * @description Complete forensic analysis of a single bundle wallet.
         */
        BundleWalletAnalysis: {
            /**
             * Wallet
             * @description Wallet public key
             */
            wallet: string;
            /**
             * Sol Spent
             * @description SOL spent buying token at launch
             * @default 0
             */
            sol_spent: number;
            pre_sell?: components["schemas"]["PreSellBehavior"];
            post_sell?: components["schemas"]["PostSellBehavior"];
            /**
             * Red Flags
             * @description Human-readable evidence flags that drove the verdict
             */
            red_flags?: string[];
            /**
             * @description Attribution verdict — only elevated when on-chain proof exists
             * @default early_buyer
             */
            verdict: components["schemas"]["BundleWalletVerdict"];
        };
        /**
         * BundleWalletVerdict
         * @description Per-wallet attribution verdict — confirmed only when on-chain proof exists.
         * @enum {string}
         */
        BundleWalletVerdict: "confirmed_team" | "suspected_team" | "coordinated_dump" | "early_buyer";
        /**
         * CartelCommunity
         * @description A detected cartel cluster — operators with 2+ coordinating signals.
         */
        CartelCommunity: {
            /**
             * Community Id
             * @description Stable 12-char hex ID derived from wallet set
             */
            community_id: string;
            /** Wallets */
            wallets: string[];
            /** Total Tokens Launched */
            total_tokens_launched: number;
            /** Total Rugs */
            total_rugs: number;
            /** Estimated Extracted Usd */
            estimated_extracted_usd: number;
            /**
             * Total Sol Extracted
             * @description Real SOL extracted from on-chain sol_flows
             * @default 0
             */
            total_sol_extracted: number;
            /**
             * Narrative
             * @description Human-readable cartel summary for the mobile app
             * @default
             */
            narrative: string;
            /** Active Since */
            active_since?: string | null;
            /**
             * Strongest Signal
             * @default
             */
            strongest_signal: string;
            /** Edges */
            edges?: components["schemas"]["CartelEdge"][];
            /**
             * Confidence
             * @default low
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /**
         * CartelEdge
         * @description A coordination signal edge between two operator wallets.
         */
        CartelEdge: {
            /** Wallet A */
            wallet_a: string;
            /** Wallet B */
            wallet_b: string;
            /**
             * Signal Type
             * @enum {string}
             */
            signal_type: "dna_match" | "sol_transfer" | "timing_sync" | "phash_cluster" | "cross_holding" | "funding_link" | "shared_lp" | "sniper_ring";
            /** Signal Strength */
            signal_strength: number;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
        };
        /**
         * CartelReport
         * @description Cartel graph result for a token's deployer.
         */
        CartelReport: {
            /** Mint */
            mint: string;
            deployer_community?: components["schemas"]["CartelCommunity"] | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ChatMessage"][];
        };
        /**
         * CrossChainExit
         * @description A detected cross-chain capital exit via a bridge program.
         */
        CrossChainExit: {
            /**
             * From Address
             * @description Solana wallet that triggered the bridge transaction
             */
            from_address: string;
            /**
             * Bridge Name
             * @description Human-readable bridge name (e.g. Wormhole Token Bridge)
             */
            bridge_name: string;
            /**
             * Dest Chain
             * @description Destination chain name (e.g. Ethereum)
             */
            dest_chain: string;
            /**
             * Dest Address
             * @description Destination wallet address on the target chain
             * @default
             */
            dest_address: string;
            /**
             * Amount Sol
             * @description SOL amount sent into the bridge
             */
            amount_sol: number;
            /**
             * Tx Signature
             * @description Solana transaction signature
             * @default
             */
            tx_signature: string;
        };
        /**
         * DataApplicability
         * @description Whether a signal is valid for the token's current context.
         * @enum {string}
         */
        DataApplicability: "observed" | "unavailable" | "not_applicable" | "conflicting";
        /**
         * DeathClockForecast
         * @description Statistical forecast of when a token may be rugged, based on deployer history.
         */
        DeathClockForecast: {
            /** Deployer */
            deployer: string;
            /** Historical Rug Count */
            historical_rug_count: number;
            /** Median Rug Hours */
            median_rug_hours: number;
            /** Stdev Rug Hours */
            stdev_rug_hours: number;
            /** Elapsed Hours */
            elapsed_hours: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high" | "critical" | "first_rug" | "insufficient_data";
            /** Predicted Window Start */
            predicted_window_start?: string | null;
            /** Predicted Window End */
            predicted_window_end?: string | null;
            /**
             * Confidence Note
             * @default
             */
            confidence_note: string;
            /**
             * Sample Count
             * @description Number of historical rug samples used
             * @default 0
             */
            sample_count: number;
            /**
             * Confidence Level
             * @description Statistical confidence in the prediction
             * @default low
             * @enum {string}
             */
            confidence_level: "low" | "medium" | "high";
            /** @description Live market signals that may elevate the risk level */
            market_signals?: components["schemas"]["MarketSignals"] | null;
            /**
             * Total Negative Outcome Count
             * @description Total rug/negative outcomes for this deployer
             * @default 0
             */
            total_negative_outcome_count: number;
            /**
             * Basis Breakdown
             * @description Rug mechanism distribution (from confirmed predictive rugs)
             */
            basis_breakdown?: {
                [key: string]: number;
            };
            /**
             * Is Factory
             * @description True when the deployer exhibits factory-like launch rhythm (new wallet per token)
             * @default false
             */
            is_factory?: boolean;
            /**
             * Prediction Basis
             * @description 'deployer' = samples from this wallet only; 'operator' = aggregated from linked wallets; 'insufficient' = no usable samples
             * @default insufficient
             * @enum {string}
             */
            prediction_basis?: "deployer" | "operator" | "insufficient";
            /**
             * Operator Sample Count
             * @description Number of rug timing samples sourced from operator-network sibling deployers
             * @default 0
             */
            operator_sample_count?: number;
            /**
             * Rug Probability Pct
             * @description Composite rug probability 0-99 combining timing, confidence and live signals. Null when no prediction possible.
             */
            rug_probability_pct?: number | null;
        };
        /**
         * DeployerProfile
         * @description Historical behaviour profile for a deployer wallet.
         */
        DeployerProfile: {
            /** Address */
            address: string;
            /** Total Tokens Launched */
            total_tokens_launched: number;
            /** Rug Count */
            rug_count: number;
            /**
             * Confirmed Rug Count
             * @description Rugs with strong/moderate evidence
             * @default 0
             */
            confirmed_rug_count: number;
            /**
             * Negative Outcome Count
             * @description Total negative outcomes (rugs + suspected)
             * @default 0
             */
            negative_outcome_count: number;
            /** Rug Rate Pct */
            rug_rate_pct: number;
            /**
             * Confirmed Rug Rate Pct
             * @default 0
             */
            confirmed_rug_rate_pct: number;
            /** Avg Lifespan Days */
            avg_lifespan_days?: number | null;
            /** Active Tokens */
            active_tokens: number;
            /** Rug Mechanism Counts */
            rug_mechanism_counts?: {
                [key: string]: number;
            };
            /**
             * Preferred Narrative
             * @default
             */
            preferred_narrative: string;
            /** First Seen */
            first_seen?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /** Tokens */
            tokens?: components["schemas"]["DeployerTokenSummary"][];
            /**
             * Confidence
             * @default low
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /**
         * DeployerTokenSummary
         * @description One token deployed by a wallet — condensed for the profile view.
         */
        DeployerTokenSummary: {
            /** Mint */
            mint: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /** Created At */
            created_at?: string | null;
            /** Rugged At */
            rugged_at?: string | null;
            /** Rug Mechanism */
            rug_mechanism?: string | null;
            /** Evidence Level */
            evidence_level?: string | null;
            /** Mcap Usd */
            mcap_usd?: number | null;
            /**
             * Narrative
             * @default
             */
            narrative: string;
        };
        /**
         * DerivativeInfo
         * @description Information about a single suspected derivative / clone.
         */
        DerivativeInfo: {
            /** Mint */
            mint: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Image Uri
             * @default
             */
            image_uri: string;
            /**
             * Deployer
             * @default
             */
            deployer: string;
            /**
             * Metadata Uri
             * @default
             */
            metadata_uri: string;
            /** Created At */
            created_at?: string | null;
            /** Market Cap Usd */
            market_cap_usd?: number | null;
            /** Liquidity Usd */
            liquidity_usd?: number | null;
            evidence?: components["schemas"]["SimilarityEvidence"];
            /**
             * Parent Mint
             * @description Mint of the direct parent (empty = child of root)
             * @default
             */
            parent_mint: string;
            /**
             * Generation
             * @description Generation depth from root (root=0, direct copy=1, copy-of-copy=2…)
             * @default 1
             */
            generation: number;
        };
        /**
         * EvidenceLevel
         * @description Strength of evidence behind a forensic conclusion.
         * @enum {string}
         */
        EvidenceLevel: "none" | "weak" | "moderate" | "strong";
        /**
         * FactoryRhythmReport
         * @description Detects statistically regular token deployment patterns (bot/script).
         */
        FactoryRhythmReport: {
            /** Tokens Launched */
            tokens_launched: number;
            /** Median Interval Hours */
            median_interval_hours: number;
            /** Regularity Score */
            regularity_score: number;
            /**
             * Naming Pattern
             * @enum {string}
             */
            naming_pattern: "incremental" | "themed" | "random";
            /** Factory Score */
            factory_score: number;
            /** Is Factory */
            is_factory: boolean;
        };
        /**
         * FinancialGraphSummary
         * @description Summary of financial coordination signals for a deployer.
         */
        FinancialGraphSummary: {
            /** Deployer */
            deployer: string;
            /**
             * Funding Links
             * @description Pre-deploy SOL funding edges found
             * @default 0
             */
            funding_links: number;
            /**
             * Shared Lp Count
             * @description Shared LP provider edges found
             * @default 0
             */
            shared_lp_count: number;
            /**
             * Sniper Ring Count
             * @description Sniper ring edges found
             * @default 0
             */
            sniper_ring_count: number;
            /**
             * Metadata Edges
             * @description Original metadata/timing signal edges
             * @default 0
             */
            metadata_edges: number;
            /**
             * Financial Score
             * @description Composite score: funding×30 + shared_lp×25 + sniper×20 + coordinated_launches×15 + metadata×10
             * @default 0
             */
            financial_score: number;
            /** Edges */
            edges?: components["schemas"]["CartelEdge"][];
            /**
             * Connected Deployers
             * @description Other deployer wallets linked via financial signals
             */
            connected_deployers?: string[];
        };
        /**
         * FundDestination
         * @description A SOL destination detected in post-sell outflow tracing.
         */
        FundDestination: {
            /** Destination */
            destination: string;
            /**
             * Lamports
             * @default 0
             */
            lamports: number;
            /**
             * Hop
             * @description 0 = direct, 1 = one hop from sell wallet
             * @default 0
             */
            hop: number;
            /**
             * Link To Deployer
             * @description Destination is deployer or deployer-linked
             * @default false
             */
            link_to_deployer: boolean;
            /**
             * Seen In Other Bundles
             * @description Same destination seen from ≥2 bundle wallets
             * @default false
             */
            seen_in_other_bundles: boolean;
        };
        /**
         * GlobalStats
         * @description Aggregate intelligence activity stats for the last 24 hours.
         */
        GlobalStats: {
            /**
             * Tokens Scanned 24H
             * @description Distinct token mints recorded
             * @default 0
             */
            tokens_scanned_24h: number;
            /**
             * Tokens Rugged 24H
             * @description Tokens confirmed rugged
             * @default 0
             */
            tokens_rugged_24h: number;
            /**
             * Rug Rate 24H Pct
             * @description rug / scanned × 100
             * @default 0
             */
            rug_rate_24h_pct: number;
            /**
             * Tokens Negative Outcomes 24H
             * @description Tokens with any negative outcome (rug + suspected) in 24 h
             * @default 0
             */
            tokens_negative_outcomes_24h: number;
            /**
             * Negative Outcome Rate 24H Pct
             * @description negative outcomes / scanned × 100
             * @default 0
             */
            negative_outcome_rate_24h_pct: number;
            /**
             * Active Deployers 24H
             * @description Distinct deployer wallets active
             * @default 0
             */
            active_deployers_24h: number;
            /**
             * Top Narratives
             * @description Top 5 narratives by token count in the last 24 h
             */
            top_narratives?: components["schemas"]["NarrativeCount"][];
            /**
             * Db Events Total
             * @description Total rows in intelligence_events table
             * @default 0
             */
            db_events_total: number;
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated?: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsiderSellEvent
         * @description A single wallet's selling activity for a specific mint.
         */
        InsiderSellEvent: {
            /**
             * Wallet
             * @description Wallet address (deployer or linked)
             */
            wallet: string;
            /**
             * Role
             * @description Relationship to the token deployer
             * @default deployer
             * @enum {string}
             */
            role: "deployer" | "linked";
            /**
             * Balance Now
             * @description Current token balance for this mint (raw UI amount)
             * @default 0
             */
            balance_now: number;
            /**
             * Exited
             * @description True when balance_now == 0 (fully exited position)
             * @default false
             */
            exited: boolean;
            /**
             * Balance Context
             * @description 'zero_balance_expected_by_protocol' for bonding-curve pre-DEX tokens
             */
            balance_context?: string | null;
        };
        /**
         * InsiderSellReport
         * @description Silent drain detection: deployer/linked wallet token selling pressure.
         */
        InsiderSellReport: {
            /** Mint */
            mint: string;
            /** Launch Platform */
            launch_platform?: string | null;
            /** @default unknown */
            lifecycle_stage: components["schemas"]["LifecycleStage"];
            /** @default no_market_observed */
            market_surface: components["schemas"]["MarketSurface"];
            /** @default unavailable */
            applicability: components["schemas"]["DataApplicability"];
            /** @default weak */
            evidence_level: components["schemas"]["EvidenceLevel"];
            /** Reason Codes */
            reason_codes?: string[];
            /**
             * Sell Pressure 1H
             * @description sells/(buys+sells) over last 1 h, 0–1
             */
            sell_pressure_1h?: number | null;
            /**
             * Sell Pressure 6H
             * @description sells/(buys+sells) over last 6 h, 0–1
             */
            sell_pressure_6h?: number | null;
            /**
             * Sell Pressure 24H
             * @description sells/(buys+sells) over last 24 h, 0–1
             */
            sell_pressure_24h?: number | null;
            /**
             * Price Change 1H
             * @description Price % change over last 1 h
             */
            price_change_1h?: number | null;
            /**
             * Price Change 6H
             * @description Price % change over last 6 h
             */
            price_change_6h?: number | null;
            /**
             * Price Change 24H
             * @description Price % change over last 24 h
             */
            price_change_24h?: number | null;
            /**
             * Volume Spike Ratio
             * @description 1 h volume divided by average hourly volume (24 h vol / 24). >3 = burst selling spike.
             */
            volume_spike_ratio?: number | null;
            /**
             * Deployer Exited
             * @description True when the deployer's token balance for this mint is 0
             */
            deployer_exited?: boolean | null;
            /**
             * Wallet Events
             * @description Per-wallet balance snapshot (deployer + up to 3 linked)
             */
            wallet_events?: components["schemas"]["InsiderSellEvent"][];
            /**
             * Flags
             * @description INSIDER_DUMP_CONFIRMED, ELEVATED_SELL_PRESSURE, PRICE_CRASH, SELL_BURST, DEPLOYER_EXITED
             */
            flags?: string[];
            /**
             * Risk Score
             * @description 0 = clean, 1.0 = confirmed insider dump
             * @default 0
             */
            risk_score: number;
            /**
             * Verdict
             * @description clean | suspicious | insider_dump
             * @default clean
             * @enum {string}
             */
            verdict: "clean" | "suspicious" | "insider_dump";
            /**
             * Is Bonding Curve
             * @description True when the token is on a bonding curve launchpad (Moonshot, PumpFun, LetsBonk). Sell pressure reflects normal user activity through the curve PDA, NOT deployer selling.
             * @default false
             */
            is_bonding_curve: boolean;
            /**
             * Platform
             * @description Platform identifier: 'moonshot', 'pump-fun', 'letsbonk', or None for DEX direct.
             */
            platform?: string | null;
        };
        /**
         * LifecycleStage
         * @description Minimal token lifecycle stages used to gate downstream signals.
         * @enum {string}
         */
        LifecycleStage: "unknown" | "launchpad_curve_only" | "migration_pending" | "dex_listed";
        /**
         * LineageResult
         * @description Full lineage detection result returned by ``detect_lineage``.
         */
        LineageResult: {
            /**
             * Mint
             * @description The queried mint address
             */
            mint: string;
            /** @description The detected root / original token */
            root?: components["schemas"]["TokenMetadata"] | null;
            /**
             * Confidence
             * @description Confidence in root selection
             * @default 0
             */
            confidence: number;
            /**
             * Derivatives
             * @description Suspected clones / derivatives
             */
            derivatives?: components["schemas"]["DerivativeInfo"][];
            /**
             * Family Size
             * @description Total family members (root + derivatives)
             * @default 0
             */
            family_size: number;
            /** @description Metadata of the queried token */
            query_token?: components["schemas"]["TokenMetadata"] | null;
            /**
             * Query Is Root
             * @description True when the scanned token IS the root (original). False means it is a clone.
             * @default false
             */
            query_is_root: boolean;
            /** @description Resurrection / zombie token detection */
            zombie_alert?: components["schemas"]["ZombieAlert"] | null;
            /** @description Deployer rug timing forecast */
            death_clock?: components["schemas"]["DeathClockForecast"] | null;
            /** @description Cross-wallet operator identity fingerprint */
            operator_fingerprint?: components["schemas"]["OperatorFingerprint"] | null;
            /** @description Cross-DEX liquidity architecture analysis */
            liquidity_arch?: components["schemas"]["LiquidityArchReport"] | null;
            /** @description Scripted deployment rhythm detection */
            factory_rhythm?: components["schemas"]["FactoryRhythmReport"] | null;
            /** @description Historical deployer behaviour profile */
            deployer_profile?: components["schemas"]["DeployerProfile"] | null;
            /** @description Cross-wallet operator damage ledger (Initiative 1) */
            operator_impact?: components["schemas"]["OperatorImpactReport"] | null;
            /** @description Post-rug SOL capital flow trace (Initiative 2) */
            sol_flow?: components["schemas"]["SolFlowReport"] | null;
            /** @description Operator cartel community detection (Initiative 3) */
            cartel_report?: components["schemas"]["CartelReport"] | null;
            /** @description Silent drain via insider token selling (Initiative 4) */
            insider_sell?: components["schemas"]["InsiderSellReport"] | null;
            /** @description Bundle wallet forensic analysis — pre+post sell behavior with verified extraction (Initiative 5) */
            bundle_report?: components["schemas"]["BundleExtractionReport"] | null;
            /**
             * Is Bonding Curve
             * @description True when token is on a bonding curve launchpad (Moonshot, PumpFun, LetsBonk).
             * @default false
             */
            is_bonding_curve: boolean;
            /**
             * Platform
             * @description Launchpad platform identifier ('moonshot', 'pump-fun', 'letsbonk') or None for DEX direct.
             */
            platform?: string | null;
            /**
             * Scanned At
             * @description UTC timestamp of when this analysis was computed (not when served from cache)
             */
            scanned_at?: string | null;
        };
        /**
         * LiquidityArchReport
         * @description Analysis of how liquidity is distributed across DEX pools.
         */
        LiquidityArchReport: {
            /** Total Liquidity Usd */
            total_liquidity_usd: number;
            /** Pool Count */
            pool_count: number;
            /** Pools */
            pools: {
                [key: string]: number;
            };
            /** Concentration Hhi */
            concentration_hhi: number;
            /** Liq To Volume Ratio */
            liq_to_volume_ratio?: number | null;
            /** Authenticity Score */
            authenticity_score: number;
            /** Flags */
            flags?: string[];
        };
        /**
         * MarketSignals
         * @description Live market health indicators used to adjust the Death Clock risk level.
         */
        MarketSignals: {
            /**
             * Liquidity Usd
             * @description Current liquidity in the main DEX pool (USD)
             */
            liquidity_usd?: number | null;
            /**
             * Market Cap Usd
             * @description Current market cap (USD)
             */
            market_cap_usd?: number | null;
            /**
             * Liq To Mcap Ratio
             * @description Liquidity / market-cap ratio (< 0.01 is suspicious)
             */
            liq_to_mcap_ratio?: number | null;
            /**
             * Price Change H1 Pct
             * @description Price change over the last hour (%)
             */
            price_change_h1_pct?: number | null;
            /**
             * Volume H1 Usd
             * @description 1-hour trading volume (USD)
             */
            volume_h1_usd?: number | null;
            /**
             * Sell Pressure Pct
             * @description % of transactions that are sells in the last hour
             */
            sell_pressure_pct?: number | null;
            /**
             * Volume Trend
             * @description Directionality of recent trading volume
             * @default stable
             * @enum {string}
             */
            volume_trend: "declining" | "stable" | "rising";
            /**
             * Adjusted Risk Boost
             * @description Additive boost applied to the timing risk_level (0 = no change, 3 = max escalation)
             * @default 0
             */
            adjusted_risk_boost: number;
        };
        /**
         * MarketSurface
         * @description Observed market surface for the token.
         * @enum {string}
         */
        MarketSurface: "no_market_observed" | "launchpad_curve_only" | "dex_pool_observed" | "conflicting";
        /** NarrativeCount */
        NarrativeCount: {
            /** Narrative */
            narrative: string;
            /** Count */
            count: number;
        };
        /**
         * OperatorFingerprint
         * @description Same metadata DNA detected across multiple deployer wallets.
         */
        OperatorFingerprint: {
            /** Fingerprint */
            fingerprint: string;
            /** Linked Wallets */
            linked_wallets: string[];
            /** Upload Service */
            upload_service: string;
            /** Description Pattern */
            description_pattern: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "confirmed" | "probable";
            /**
             * Linked Wallet Tokens
             * @description Tokens launched by each linked wallet (from intelligence_events)
             */
            linked_wallet_tokens?: {
                [key: string]: components["schemas"]["DeployerTokenSummary"][];
            };
        };
        /**
         * OperatorImpactReport
         * @description Cross-wallet damage ledger for an operator sharing a metadata DNA fingerprint.
         */
        OperatorImpactReport: {
            /**
             * Fingerprint
             * @description The 32-char hex DNA fingerprint
             */
            fingerprint: string;
            /**
             * Linked Wallets
             * @description All deployer wallets sharing this fingerprint
             */
            linked_wallets: string[];
            /** Total Tokens Launched */
            total_tokens_launched: number;
            /** Total Rug Count */
            total_rug_count: number;
            /**
             * Total Confirmed Rug Count
             * @description Rugs with strong/moderate evidence
             * @default 0
             */
            total_confirmed_rug_count: number;
            /**
             * Total Negative Outcome Count
             * @description Total negative outcomes
             * @default 0
             */
            total_negative_outcome_count: number;
            /** Rug Rate Pct */
            rug_rate_pct: number;
            /**
             * Confirmed Rug Rate Pct
             * @default 0
             */
            confirmed_rug_rate_pct: number;
            /**
             * Estimated Extracted Usd
             * @description Conservative 15% of rugged mcap estimate
             */
            estimated_extracted_usd: number;
            /**
             * Is Estimated
             * @description True if extraction figure is a 15% heuristic, False if from on-chain trace
             * @default true
             */
            is_estimated: boolean;
            /** Rug Mechanism Counts */
            rug_mechanism_counts?: {
                [key: string]: number;
            };
            /**
             * Active Tokens
             * @description Mints still not rugged
             */
            active_tokens?: string[];
            /**
             * Narrative Sequence
             * @description Narratives exploited, in chronological order of first appearance
             */
            narrative_sequence?: string[];
            /**
             * Is Campaign Active
             * @description True if any wallet had activity in the last 6 hours
             * @default false
             */
            is_campaign_active: boolean;
            /**
             * Peak Concurrent Tokens
             * @description Max tokens live simultaneously within a 24h window
             * @default 0
             */
            peak_concurrent_tokens: number;
            /** First Activity */
            first_activity?: string | null;
            /** Last Activity */
            last_activity?: string | null;
            /** Wallet Profiles */
            wallet_profiles?: components["schemas"]["DeployerProfile"][];
            /**
             * Confidence
             * @default low
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /**
         * PostSellBehavior
         * @description Behavior of a bundle wallet AFTER selling its token position.
         */
        PostSellBehavior: {
            /**
             * Sell Detected
             * @description On-chain full-exit sell confirmed
             * @default false
             */
            sell_detected: boolean;
            /**
             * Sell Slot
             * @description Slot of the detected sell transaction
             */
            sell_slot?: number | null;
            /**
             * Sell Tx Signature
             * @description Signature of the sell transaction
             */
            sell_tx_signature?: string | null;
            /**
             * Sol Received From Sell
             * @description SOL received when selling
             * @default 0
             */
            sol_received_from_sell: number;
            /**
             * Fund Destinations
             * @description SOL destinations traced ≤2 hops after sell, only post-sell txs
             */
            fund_destinations?: components["schemas"]["FundDestination"][];
            /**
             * Direct Transfer To Deployer
             * @description Wallet sent SOL directly to deployer after selling
             * @default false
             */
            direct_transfer_to_deployer: boolean;
            /**
             * Transfer To Deployer Linked Wallet
             * @description Wallet sent SOL to a wallet also linked to deployer
             * @default false
             */
            transfer_to_deployer_linked_wallet: boolean;
            /**
             * Indirect Via Intermediary
             * @description Multi-hop path from this wallet back to deployer confirmed
             * @default false
             */
            indirect_via_intermediary: boolean;
            /**
             * Common Destination With Other Bundles
             * @description ≥2 bundle wallets sent SOL to the same destination
             * @default false
             */
            common_destination_with_other_bundles: boolean;
        };
        /**
         * PreSellBehavior
         * @description Behavior of a bundle wallet BEFORE selling its token position.
         */
        PreSellBehavior: {
            /**
             * Wallet Age Days
             * @description Days since first on-chain activity
             */
            wallet_age_days?: number | null;
            /**
             * Is Dormant
             * @description True if wallet had no activity for >30 days before launch
             * @default false
             */
            is_dormant: boolean;
            /**
             * Prefund Source
             * @description Address that funded this wallet before launch
             */
            prefund_source?: string | null;
            /**
             * Prefund Sol
             * @description SOL received in funding transfer
             * @default 0
             */
            prefund_sol: number;
            /**
             * Prefund Hours Before Launch
             * @description Hours between funding and launch
             */
            prefund_hours_before_launch?: number | null;
            /**
             * Prefund Source Is Deployer
             * @description Prefund source is the token deployer
             * @default false
             */
            prefund_source_is_deployer: boolean;
            /**
             * Prefund Source Is Known Funder
             * @description Prefund source also funded other bundle wallets
             * @default false
             */
            prefund_source_is_known_funder: boolean;
            /**
             * Pre Launch Tx Count
             * @description Number of txs in 72h before launch
             * @default 0
             */
            pre_launch_tx_count: number;
            /**
             * Pre Launch Unique Tokens
             * @description Unique token mints interacted with before launch
             * @default 0
             */
            pre_launch_unique_tokens: number;
            /**
             * Prior Bundle Count
             * @description Times this wallet appeared in earlier bundles (any deployer)
             * @default 0
             */
            prior_bundle_count: number;
            /**
             * Same Deployer Prior Launches
             * @description Prior launches by same deployer where this wallet bundled
             * @default 0
             */
            same_deployer_prior_launches: number;
        };
        /**
         * SimilarityEvidence
         * @description Per-dimension similarity scores between two tokens.
         */
        SimilarityEvidence: {
            /**
             * Name Score
             * @default 0
             */
            name_score: number;
            /**
             * Symbol Score
             * @default 0
             */
            symbol_score: number;
            /**
             * Image Score
             * @default 0
             */
            image_score: number;
            /**
             * Deployer Score
             * @default 0
             */
            deployer_score: number;
            /**
             * Temporal Score
             * @default 0
             */
            temporal_score: number;
            /**
             * Composite Score
             * @default 0
             */
            composite_score: number;
        };
        /**
         * SolFlowEdge
         * @description A single SOL transfer edge in the post-rug capital flow graph.
         */
        SolFlowEdge: {
            /** From Address */
            from_address: string;
            /** To Address */
            to_address: string;
            /** Amount Sol */
            amount_sol: number;
            /**
             * Hop
             * @description 0 = direct from deployer, 1 = one hop away, etc.
             */
            hop: number;
            /**
             * Signature
             * @description Transaction signature
             * @default
             */
            signature: string;
            /** Block Time */
            block_time?: string | null;
            /**
             * From Label
             * @description Human-readable label for from_address
             */
            from_label?: string | null;
            /**
             * To Label
             * @description Human-readable label for to_address
             */
            to_label?: string | null;
            /**
             * Entity Type
             * @description Entity type of to_address (cex, dex, bridge, …)
             */
            entity_type?: string | null;
        };
        /**
         * SolFlowReport
         * @description Multi-hop SOL capital flow trace for a rugged token.
         */
        SolFlowReport: {
            /** Mint */
            mint: string;
            /** Deployer */
            deployer: string;
            /**
             * Total Extracted Sol
             * @description Direct SOL outflows from deployer (hop 0)
             */
            total_extracted_sol: number;
            /**
             * Total Extracted Usd
             * @description USD value at time of extraction (SOL × market price)
             */
            total_extracted_usd?: number | null;
            /** Flows */
            flows?: components["schemas"]["SolFlowEdge"][];
            /**
             * Terminal Wallets
             * @description Final destination wallets never seen as senders
             */
            terminal_wallets?: string[];
            /**
             * Known Cex Detected
             * @description True if any known CEX hot wallet is a recipient
             * @default false
             */
            known_cex_detected: boolean;
            /**
             * Hop Count
             * @description Deepest hop reached
             * @default 1
             */
            hop_count: number;
            /**
             * Analysis Timestamp
             * Format: date-time
             */
            analysis_timestamp: string;
            /**
             * Rug Timestamp
             * @description Earliest block_time of hop-0 flows (first moment of extraction)
             */
            rug_timestamp?: string | null;
            /**
             * Cross Chain Exits
             * @description Detected cross-chain bridge exits
             */
            cross_chain_exits?: components["schemas"]["CrossChainExit"][];
            /**
             * Liquidity Is Sol Denominated
             * @description False when all trading pairs use USDC/non-SOL as quote token. When False, SOL flows represent infrastructure costs (rent, fees, launchpad), not value extraction — actual extraction would appear via USDC.
             * @default true
             */
            liquidity_is_sol_denominated: boolean;
        };
        /**
         * TokenCompareResult
         * @description Side-by-side similarity analysis between two tokens.
         */
        TokenCompareResult: {
            /** Mint A */
            mint_a: string;
            /** Mint B */
            mint_b: string;
            token_a?: components["schemas"]["TokenMetadata"] | null;
            token_b?: components["schemas"]["TokenMetadata"] | null;
            /**
             * Same Deployer
             * @default false
             */
            same_deployer: boolean;
            /**
             * Same Family
             * @description True if one token appears in the lineage derivatives of the other
             * @default false
             */
            same_family: boolean;
            /**
             * Name Similarity
             * @default 0
             */
            name_similarity: number;
            /**
             * Symbol Similarity
             * @default 0
             */
            symbol_similarity: number;
            /**
             * Image Similarity
             * @description -1 = no image URL, -2 = image fetch failed/timed-out, [0,1] = similarity score
             * @default -1
             */
            image_similarity: number;
            /**
             * Temporal Score
             * @description Directional age signal: 1.0 = token_a is significantly older, 0.5 = same age / unknown, 0.0 = token_a is significantly newer
             * @default 0.5
             */
            temporal_score: number;
            /**
             * Metadata Uri Match
             * @description Both tokens share the exact same on-chain metadata URI
             * @default false
             */
            metadata_uri_match: boolean;
            /**
             * Image Url Match
             * @description Both tokens share the exact same image URL
             * @default false
             */
            image_url_match: boolean;
            /**
             * Same Token Program
             * @description Both mints are owned by the same non-standard SPL program (custom token program)
             * @default false
             */
            same_token_program: boolean;
            /**
             * Composite Score
             * @description Weighted composite of name + symbol + image + temporal signals
             * @default 0
             */
            composite_score: number;
            /**
             * Verdict
             * @default unrelated
             * @enum {string}
             */
            verdict: "identical_operator" | "clone" | "related" | "unrelated";
            /**
             * Verdict Reasons
             * @description Human-readable explanations for the verdict
             */
            verdict_reasons?: string[];
        };
        /**
         * TokenMetadata
         * @description On‑chain and off‑chain metadata for a single token.
         */
        TokenMetadata: {
            /**
             * Mint
             * @description Solana mint address
             */
            mint: string;
            /**
             * Name
             * @description Human-readable token name
             * @default
             */
            name: string;
            /**
             * Symbol
             * @description Ticker / symbol
             * @default
             */
            symbol: string;
            /**
             * Image Uri
             * @description URL to the token logo
             * @default
             */
            image_uri: string;
            /**
             * Deployer
             * @description Address that deployed/created the token
             * @default
             */
            deployer: string;
            /**
             * Created At
             * @description On-chain creation timestamp
             */
            created_at?: string | null;
            /**
             * Market Cap Usd
             * @description Current market capitalisation in USD
             */
            market_cap_usd?: number | null;
            /**
             * Liquidity Usd
             * @description Total liquidity in USD
             */
            liquidity_usd?: number | null;
            /**
             * Price Usd
             * @description Current token price in USD
             */
            price_usd?: number | null;
            /**
             * Dex Url
             * @description DexScreener URL for this token
             * @default
             */
            dex_url: string;
            /**
             * Metadata Uri
             * @description Metaplex metadata URI (off-chain JSON)
             * @default
             */
            metadata_uri: string;
            /**
             * Token Standard
             * @description Token standard from DAS (Fungible, FungibleAsset, etc.)
             * @default
             */
            token_standard: string;
            /**
             * Pair Created At
             * @description Earliest DexScreener pairCreatedAt — when the token was first listed on a DEX. Distinct from created_at which reflects the on-chain mint initialisation. When pair_created_at >> created_at the token was stealth pre-minted.
             */
            pair_created_at?: string | null;
            /**
             * Launch Platform
             * @description Detected launch platform (moonshot, pumpfun, letsbonk, believe) when known
             */
            launch_platform?: string | null;
            /**
             * @description Minimal lifecycle stage used to validate downstream forensic signals
             * @default unknown
             */
            lifecycle_stage: components["schemas"]["LifecycleStage"];
            /**
             * @description Observed market surface for this token at scan time
             * @default no_market_observed
             */
            market_surface: components["schemas"]["MarketSurface"];
            /**
             * Reason Codes
             * @description Short deterministic reasons explaining platform/stage classification
             */
            reason_codes?: string[];
            /**
             * @description Strength of evidence supporting the market context classification
             * @default weak
             */
            evidence_level: components["schemas"]["EvidenceLevel"];
        };
        /**
         * TokenSearchResult
         * @description A token returned from a search query.
         */
        TokenSearchResult: {
            /** Mint */
            mint: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Symbol
             * @default
             */
            symbol: string;
            /**
             * Image Uri
             * @default
             */
            image_uri: string;
            /**
             * Metadata Uri
             * @default
             */
            metadata_uri: string;
            /** Price Usd */
            price_usd?: number | null;
            /** Market Cap Usd */
            market_cap_usd?: number | null;
            /** Liquidity Usd */
            liquidity_usd?: number | null;
            /**
             * Dex Url
             * @default
             */
            dex_url: string;
            /** Pair Created At */
            pair_created_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ZombieAlert
         * @description A dead token that has been relaunched by the same (or similar) operator.
         */
        ZombieAlert: {
            /** Original Mint */
            original_mint: string;
            /** Original Name */
            original_name: string;
            /** Original Rugged At */
            original_rugged_at?: string | null;
            /** Original Liq Peak Usd */
            original_liq_peak_usd?: number | null;
            /** Resurrection Mint */
            resurrection_mint: string;
            /** Image Similarity */
            image_similarity: number;
            /** Same Deployer */
            same_deployer: boolean;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "confirmed" | "probable" | "possible";
        };
        /** _LoginRequest */
        _LoginRequest: {
            /** Privy Id */
            privy_id: string;
            /** Wallet Address */
            wallet_address?: string | null;
            /** Email */
            email?: string | null;
        };
        /** _WatchRequest */
        _WatchRequest: {
            /** Sub Type */
            sub_type: string;
            /** Value */
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admin_health_admin_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_lineage_lineage_get: {
        parameters: {
            query: {
                /** @description Solana mint address of the token */
                mint: string;
                /** @description Bust cache and re-run full analysis */
                force_refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_lineage_lineage_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchLineageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchLineageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description Token name or symbol to search */
                q: string;
                /** @description Max results to return */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployer_profile_deployer__address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operator_impact_operator__fingerprint__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fingerprint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorImpactReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sol_trace_lineage__mint__sol_trace_get: {
        parameters: {
            query?: {
                /** @description Bypass DB cache and re-trace */
                force_refresh?: boolean;
            };
            header?: never;
            path: {
                mint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolFlowReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_bundle_lineage__mint__bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleExtractionReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cartel_search_cartel_search_get: {
        parameters: {
            query: {
                /** @description Deployer wallet address */
                deployer: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartelReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cartel_community_cartel__community_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                community_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartelCommunity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cartel_financial_graph_cartel__deployer__financial_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialGraphSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bundle_report_bundle__mint__get: {
        parameters: {
            query?: {
                deployer?: string | null;
                force_refresh?: boolean;
            };
            header?: never;
            path: {
                mint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleExtractionReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_graph_lineage__mint__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_analysis_analyze__mint__get: {
        parameters: {
            query?: {
                /** @description Re-run AI analysis even if cached */
                force_refresh?: boolean;
            };
            header?: never;
            path: {
                mint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_ai_analysis_analyze__mint__stream_get: {
        parameters: {
            query?: {
                /** @description Re-run AI analysis even if cached */
                force_refresh?: boolean;
            };
            header?: never;
            path: {
                mint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forensic_chat_chat__mint__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mint: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_watches_auth_watches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_add_watch_auth_watches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_WatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_remove_watch_auth_watches__watch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_tokens_compare_get: {
        parameters: {
            query: {
                /** @description First Solana mint address */
                mint_a: string;
                /** @description Second Solana mint address */
                mint_b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCompareResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_global_stats_stats_global_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStats"];
                };
            };
        };
    };
    get_stats_brief_stats_brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
