"""Export service — generates token analysis reports."""
from __future__ import annotations
import html
import logging
import time

logger = logging.getLogger(__name__)


def generate_html_report(lineage_result: dict) -> str:
    """Generate an HTML report from a LineageResult dict."""
    qt = lineage_result.get("query_token") or lineage_result.get("root") or {}
    dc = lineage_result.get("death_clock") or {}
    dp = lineage_result.get("deployer_profile") or {}
    sf = lineage_result.get("sol_flow") or {}
    ins = lineage_result.get("insider_sell") or {}

    name = html.escape(qt.get("name", "Unknown"))
    symbol = html.escape(qt.get("symbol", ""))
    mint = html.escape(qt.get("mint", lineage_result.get("mint", "")))
    mcap = qt.get("market_cap_usd")
    liq = qt.get("liquidity_usd")

    risk = dc.get("risk_level", "unknown")
    rug_prob = dc.get("rug_probability_pct")
    deployer = html.escape(dp.get("address", ""))
    rug_rate = dp.get("rug_rate_pct", 0)
    sol_extracted = sf.get("total_extracted_sol")

    mcap_str = f"${mcap:,.0f}" if mcap else "N/A"
    liq_str = f"${liq:,.0f}" if liq else "N/A"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>Lineage Report — {name}</title>
<style>
body {{ font-family: -apple-system, sans-serif; background: #0a0e1a; color: #e0e0e0; padding: 20px; }}
h1 {{ color: #ADC8FF; }} h2 {{ color: #8899bb; border-bottom: 1px solid #222; padding-bottom: 4px; }}
.badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }}
.risk-low {{ background: #00FF8820; color: #00FF88; }}
.risk-medium {{ background: #F59E0B20; color: #F59E0B; }}
.risk-high {{ background: #FF993320; color: #FF9933; }}
.risk-critical {{ background: #FF336620; color: #FF3366; }}
table {{ width: 100%; border-collapse: collapse; margin: 8px 0; }}
td {{ padding: 6px 0; border-bottom: 1px solid #1a1f30; }}
td:first-child {{ color: #8899bb; width: 40%; }}
.footer {{ margin-top: 24px; font-size: 11px; color: #555; text-align: center; }}
</style></head><body>
<h1>{name} ({symbol})</h1>
<p><code>{mint}</code></p>
<span class="badge risk-{risk}">{risk.upper()}</span>

<h2>Market Data</h2>
<table>
<tr><td>Market Cap</td><td>{mcap_str}</td></tr>
<tr><td>Liquidity</td><td>{liq_str}</td></tr>
</table>

<h2>Death Clock</h2>
<table>
<tr><td>Risk Level</td><td>{risk}</td></tr>
<tr><td>Rug Probability</td><td>{f'{rug_prob}%' if rug_prob is not None else 'N/A'}</td></tr>
</table>

<h2>Deployer</h2>
<table>
<tr><td>Address</td><td><code>{deployer}</code></td></tr>
<tr><td>Rug Rate</td><td>{rug_rate:.1f}%</td></tr>
<tr><td>Total Tokens</td><td>{dp.get('total_tokens_launched', 'N/A')}</td></tr>
</table>

<h2>SOL Flow</h2>
<table>
<tr><td>Extracted</td><td>{f'{sol_extracted:.2f} SOL' if sol_extracted else 'N/A'}</td></tr>
<tr><td>Hops</td><td>{sf.get('hop_count', 'N/A')}</td></tr>
</table>

<h2>Insider Activity</h2>
<table>
<tr><td>Verdict</td><td>{ins.get('verdict', 'N/A')}</td></tr>
<tr><td>Deployer Exited</td><td>{ins.get('deployer_exited', 'N/A')}</td></tr>
</table>

<div class="footer">
Generated by Lineage Agent · {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}
</div>
</body></html>"""
